version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: patente
      DB_USER: admin
      DB_PASS: admin
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patente
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql:ro
volumes:
  db_data:


